# Generated by Django 3.2.4 on 2021-06-26 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('culture_blog', '0004_auto_20210626_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 11, 38, 29, 856018, tzinfo=utc)),
        ),
    ]
